import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const main = localFont({
  src: [
    {
      path: "./fonts/PPPangaia-Bold.otf",
      weight: "700",
      style: "bold",
    },
  ],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={main.className}>{children}</body>
    </html>
  );
}
