/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/q6wbi4szbwe
 */
import {
  CardDescription,
  CardTitle,
  CardHeader,
  CardContent,
  Card,
} from "@/components/ui/card";
import { Avatar } from "@/components/ui/avatar";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export function ChatAI() {
  return (
    <Card>
      <CardHeader>
        <CardDescription>Chat Interface</CardDescription>
        <CardTitle>AI Chat</CardTitle>
      </CardHeader>
      <CardContent className="flex flex-col gap-4">
        <div className="flex items-start">
          <Avatar
            className="w-10 h-10 rounded-full"
            src="/placeholder-avatar.jpg"
          />
          <div className="bg-gray-100 dark:bg-gray-800 p-3 rounded-lg max-w-[70%]">
            <p className="text-sm">Hello! How can I assist you today?</p>
          </div>
        </div>
        <div className="flex items-end justify-end">
          <div className="bg-gray-100 dark:bg-gray-800 p-3 rounded-lg max-w-[70%]">
            <p className="text-sm">
              Sure, I can help with that. Please provide more details.
            </p>
          </div>
          <Avatar
            className="w-10 h-10 rounded-full"
            src="/placeholder-avatar.jpg"
          />
        </div>
        <div className="flex items-start">
          <Avatar
            className="w-10 h-10 rounded-full"
            src="/placeholder-avatar.jpg"
          />
          <div className="bg-gray-100 dark:bg-gray-800 p-3 rounded-lg max-w-[70%]">
            <p className="text-sm">
              Let me check that for you. One moment, please.
            </p>
          </div>
        </div>
        <div className="flex items-center gap-4">
          <Input
            className="flex-1"
            placeholder="Type your message..."
            type="text"
          />
          <Button className="bg-blue-800" type="submit">
            Send
          </Button>
        </div>
        <div className="bg-gray-100 dark:bg-gray-800 p-3 rounded-lg max-w-[70%]">
          <p className="text-sm">Previous Chat History...</p>
        </div>
      </CardContent>
    </Card>
  );
}
